package wsdl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2018-01-29T17:24:29.473+08:00
 * Generated source version: 3.2.1
 * 
 */
@WebService(targetNamespace = "http://service.finance.hbmcc.huawei.com/", name = "IMsgThreeElements")
@XmlSeeAlso({ObjectFactory.class})
public interface IMsgThreeElements {

    @WebMethod
    @RequestWrapper(localName = "validatePhoneNoIdCardCustNameSame", targetNamespace = "http://service.finance.hbmcc.huawei.com/", className = "wsdl.ValidatePhoneNoIdCardCustNameSame")
    @ResponseWrapper(localName = "validatePhoneNoIdCardCustNameSameResponse", targetNamespace = "http://service.finance.hbmcc.huawei.com/", className = "wsdl.ValidatePhoneNoIdCardCustNameSameResponse")
    @WebResult(name = "return", targetNamespace = "")
    public String validatePhoneNoIdCardCustNameSame(
		    @WebParam(name = "userNo", targetNamespace = "")
				    String userNo,
		    @WebParam(name = "userPwd", targetNamespace = "")
				    String userPwd,
		    @WebParam(name = "phoneNo", targetNamespace = "")
				    String phoneNo,
		    @WebParam(name = "custName", targetNamespace = "")
				    String custName,
		    @WebParam(name = "idCard", targetNamespace = "")
				    String idCard
    );

    @WebMethod
    @RequestWrapper(localName = "validatePhoneNoAndIdCardSame", targetNamespace = "http://service.finance.hbmcc.huawei.com/", className = "wsdl.ValidatePhoneNoAndIdCardSame")
    @ResponseWrapper(localName = "validatePhoneNoAndIdCardSameResponse", targetNamespace = "http://service.finance.hbmcc.huawei.com/", className = "wsdl.ValidatePhoneNoAndIdCardSameResponse")
    @WebResult(name = "return", targetNamespace = "")
    public String validatePhoneNoAndIdCardSame(
		    @WebParam(name = "userNo", targetNamespace = "")
				    String userNo,
		    @WebParam(name = "userPwd", targetNamespace = "")
				    String userPwd,
		    @WebParam(name = "phoneNo", targetNamespace = "")
				    String phoneNo,
		    @WebParam(name = "idCard", targetNamespace = "")
				    String idCard
    );

    @WebMethod
    @RequestWrapper(localName = "validatePhoneNoAndCustNameSame", targetNamespace = "http://service.finance.hbmcc.huawei.com/", className = "wsdl.ValidatePhoneNoAndCustNameSame")
    @ResponseWrapper(localName = "validatePhoneNoAndCustNameSameResponse", targetNamespace = "http://service.finance.hbmcc.huawei.com/", className = "wsdl.ValidatePhoneNoAndCustNameSameResponse")
    @WebResult(name = "return", targetNamespace = "")
    public String validatePhoneNoAndCustNameSame(
		    @WebParam(name = "userNo", targetNamespace = "")
				    String userNo,
		    @WebParam(name = "userPwd", targetNamespace = "")
				    String userPwd,
		    @WebParam(name = "phoneNo", targetNamespace = "")
				    String phoneNo,
		    @WebParam(name = "custName", targetNamespace = "")
				    String custName
    );
}
