package wsdl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2018-01-29T17:24:29.488+08:00
 * Generated source version: 3.2.1
 * 
 */
@WebServiceClient(name = "IMsgThreeElements", 
                  wsdlLocation = "http://218.207.75.11/HBMCC_INF/webservice/validateElements?wsdl",
                  targetNamespace = "http://service.finance.hbmcc.huawei.com/") 
public class IMsgThreeElements_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://service.finance.hbmcc.huawei.com/", "IMsgThreeElements");
    public final static QName IMsgThreeElementsPort = new QName("http://service.finance.hbmcc.huawei.com/", "IMsgThreeElementsPort");
    static {
        URL url = null;
        try {
            url = new URL("http://218.207.75.11/HBMCC_INF/webservice/validateElements?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(IMsgThreeElements_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://218.207.75.11/HBMCC_INF/webservice/validateElements?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public IMsgThreeElements_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public IMsgThreeElements_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IMsgThreeElements_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public IMsgThreeElements_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public IMsgThreeElements_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public IMsgThreeElements_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns IMsgThreeElements
     */
    @WebEndpoint(name = "IMsgThreeElementsPort")
    public IMsgThreeElements getIMsgThreeElementsPort() {
        return super.getPort(IMsgThreeElementsPort, IMsgThreeElements.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IMsgThreeElements
     */
    @WebEndpoint(name = "IMsgThreeElementsPort")
    public IMsgThreeElements getIMsgThreeElementsPort(WebServiceFeature... features) {
        return super.getPort(IMsgThreeElementsPort, IMsgThreeElements.class, features);
    }

}
