
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package wsdl;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2018-01-29T17:24:29.449+08:00
 * Generated source version: 3.2.1
 * 
 */

@WebService(
                      serviceName = "IMsgThreeElements",
                      portName = "IMsgThreeElementsPort",
                      targetNamespace = "http://service.finance.hbmcc.huawei.com/",
                      wsdlLocation = "http://218.207.75.11/HBMCC_INF/webservice/validateElements?wsdl",
                      endpointInterface = "wsdl.IMsgThreeElements")
                      
public class IMsgThreeElementsPortImpl implements IMsgThreeElements {

    private static final Logger LOG = Logger.getLogger(IMsgThreeElementsPortImpl.class.getName());

    /* (non-Javadoc)
     * @see wsdl.IMsgThreeElements#validatePhoneNoIdCardCustNameSame(java.lang.String userNo, java.lang.String userPwd, java.lang.String phoneNo, java.lang.String custName, java.lang.String idCard)*
     */
    public String validatePhoneNoIdCardCustNameSame(String userNo, String userPwd, String phoneNo, String custName, String idCard) {
        LOG.info("Executing operation validatePhoneNoIdCardCustNameSame");
        System.out.println(userNo);
        System.out.println(userPwd);
        System.out.println(phoneNo);
        System.out.println(custName);
        System.out.println(idCard);
        try {
            String _return = "";
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see wsdl.IMsgThreeElements#validatePhoneNoAndIdCardSame(java.lang.String userNo, java.lang.String userPwd, java.lang.String phoneNo, java.lang.String idCard)*
     */
    public String validatePhoneNoAndIdCardSame(String userNo, String userPwd, String phoneNo, String idCard) {
        LOG.info("Executing operation validatePhoneNoAndIdCardSame");
        System.out.println(userNo);
        System.out.println(userPwd);
        System.out.println(phoneNo);
        System.out.println(idCard);
        try {
            String _return = "";
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see wsdl.IMsgThreeElements#validatePhoneNoAndCustNameSame(java.lang.String userNo, java.lang.String userPwd, java.lang.String phoneNo, java.lang.String custName)*
     */
    public String validatePhoneNoAndCustNameSame(String userNo, String userPwd, String phoneNo, String custName) {
        LOG.info("Executing operation validatePhoneNoAndCustNameSame");
        System.out.println(userNo);
        System.out.println(userPwd);
        System.out.println(phoneNo);
        System.out.println(custName);
        try {
            String _return = "";
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
